# Generated by Django 5.0.7 on 2024-07-13 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
